[options]
    enable_statusline_mode = true
    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = true
    statusline_unicode_symbols = true
    line_on_the_fly = false

[[layers]]
    name = 'core'
    enable_filetree_gitstatus = true
    enable_filetree_filetypeicon = true

[[layers]]
    name = "autocomplete"
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "cycle"

[[layers]]
    name = "shell"
    default_position = "top"
    default_height = 30
